### ISSUE TITLE
[service support] kube-dns pod: verify it is able to respond DNS queries of kubernetes, and kubernetes_{network}, and other service names

### ISSUE THREAD

**Issue by h-w-chen** [CentaurusInfra/arktos#1144]
**What would you like to be added**:
use dig tool to query against DNS pod ip. Refer to [PR deploy per-network DNS](https://github.com/CentaurusInfra/arktos/pull/509) for sample of dig command.

**Why is this needed**:
to verify DNS pods able to handle DNS queries as expected

**Comment by h-w-chen** [comment]
in scale-up cluster, after arktos-network-controller has been successfully started,

1. create a test tenant ``` kubectl create tenant test1```
2. in the test tenant, create a custom network object 
```
cat << EOF | kubectl apply --enant test1 -f -
apiVersion: arktos.futurewei.com/v1
kind: Network
metadata:
  name: my-net
spec:
  type: flat
EOF
```
3. in the test tenant, create a service object, associating it to the network object
```
cat << EOF | kubectl create --tenant test1 -f -
apiVersion: v1
kind: Service
metadata:
  name: my-svc
  labels:
    app: my-svc
    arktos.futurewei.com/network: my-net
spec:
  type: ClusterIP
  ports:
  - name: 8888-80
    port: 8888
    protocol: TCP
    targetPort: 80
  selector:
    app: my-svc
EOF
```
4. query the network specific DNS pod for following names, verifying they have proper IP responded, respectively

| name | ip expected |
| --- | --- |
| kubernetes-default.default.svc.cluster.local | IP of service test1/default/kubernetes-default |
| kubernetes.default.svc.cluster.local | IP of service test1/default/kubernetes-default |
| kube-dns-default.kube-system.svc.cluster.local | IP of service test1/kube-system/kube-dns-default |
| kube-dns.kube-system.svc.cluster.local | IP of service test1/kube-system/kube-dns-default |
| my-svc.default.svc.cluster.local | IP of test1/default/my-svc |

**Comment by q131172019** [comment]
First create 1 TP X 1 RP scale-out cluster with flannel network plugin and arktos network controller on AWS:

On TP1: after rebooting EC2 instance, follow up the following procedure to get TP1 up
```
cat /home/ubuntu/TMP/default_network.tmpl

{
    "metadata": {
        "name": "default"
    },
    "spec": {
        "type": "flat"
    }
}


export ARKTOS_NETWORK_TEMPLATE=/home/ubuntu/TMP/default_network.tmpl  -- TP2 is not up because "export RESOURCE_SERVER=172.31.5.191" is using wrong IP of TP2


sudo chmod o+rw /var/run/docker.sock; ls -alg /var/run/docker.sock
sudo rm -rf /opt/cni/bin/*; sudo ls -alg /opt/cni/bin/
sudo rm -rf /etc/cni/net.d/*; sudo ls -alg /etc/cni/net.d/
sudo rm -rf /etc/cni/net.d/10-flannel.conflist; sudo ls -alg /etc/cni/net.d/
sudo rm -rf /etc/cni/net.d/bridge.conf; sudo ls -alg /etc/cni/net.d/

sudo make clean
make clean


export ARKTOS_NO_CNI_PREINSTALLED=y
export IS_RESOURCE_PARTITION=false
export RESOURCE_SERVER=172.31.13.237

./hack/arktos-up-scale-out-poc.sh
<snip>
Tenant Partition Cluster is Running ...
```

**Comment by q131172019** [comment]
Finally get to here to do verification for this issue #1144:

--- create a test tenant ``` kubectl create tenant test1```
--- in the test tenant, create a custom network object 
```
cat << EOF | kubectl apply --tenant test1 -f -
apiVersion: arktos.futurewei.com/v1
kind: Network
metadata:
  name: my-net
spec:
  type: flat
EOF
```
--- in the test tenant, create a service object, associating it to the network object
```
cat << EOF | kubectl create --tenant test1 -f -
apiVersion: v1
kind: Service
metadata:
  name: my-svc
  labels:
    app: my-svc
    arktos.futurewei.com/network: my-net
spec:
  type: ClusterIP
  ports:
  - name: 8888-80
    port: 8888
    protocol: TCP
    targetPort: 80
  selector:
    app: my-svc
EOF
```
--- query the network specific DNS pod for following names, verifying they have proper IP responded, respectively
| name | ip expected |
| --- | --- |
| kubernetes-default.default.svc.cluster.local | IP of service test1/default/kubernetes-default |
| kubernetes.default.svc.cluster.local | IP of service test1/default/kubernetes-default |
| kube-dns-default.kube-system.svc.cluster.local | IP of service test1/kube-system/kube-dns-default |
| kube-dns.kube-system.svc.cluster.local | IP of service test1/kube-system/kube-dns-default |
| my-svc.default.svc.cluster.local | IP of test1/default/my-svc |
