### ISSUE TITLE
[service support] deployment/RS/pod: ensure network label is assigned properly

### ISSUE THREAD

**Issue by h-w-chen** [CentaurusInfra/arktos#1146]
**What would you like to be added**:
1. create a deployment in a certain network;
2. verify RS object created has same network property;
3. verify pods created have same network property

**Why is this needed**:
to ensure deploy/RS controller respect network property

This is UX related - when users define deployment, the network association (by means of network label) can be allowed to specify at deployment metadata, no need for repetitive definition of pod template. 

It ensures pods of  deployment will inherit its network as well. Without this enforcement, deployment could have pods of different network.

**Comment by h-w-chen** [comment]
to create a deployment associated to certain network:
```
cat << EOF | kubectl apply -f -
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
    arktos.futurewei.com/network: mynet
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
EOF
```
