### ISSUE TITLE
[POC] Create a VPC/subnet manually, delete subnet stuck

### ISSUE THREAD

**Issue by Sindica** [CentaurusInfra/arktos#1287]
**What happened**:
Manually created mizar VPC/subnet. No pod attached to it. Try delete subnet with kubectl, kubectl stuck

**What you expected to happen**:
kubectl should return quickly

**How to reproduce it (as minimally and precisely as possible)**:
. Create VPC/subnet using kubectl:
```
apiVersion: mizar.com/v1
kind: Vpc
metadata:
  name: vpc-ying
spec:
  ip: "22.0.0.0"
  prefix: "16"
  dividers: 1
  status: "Init"
---
apiVersion: mizar.com/v1
kind: Subnet
metadata:
  name: net-ying
spec:
  ip: "22.0.1.0"
  prefix: "24"
  bouncers: 1
  vpc: "vpc-ying"
  status: "Init"
```

. Delete subnet using kubectl
```
./cluster/kubectl.sh delete -f ~/mizar-integ/vpc/subnet.yaml
```
